package euler.problem0029

import euler.bigInt
import java.math.BigInteger

fun main(args: Array<String>) {
  val min = 2; val max = 100; val range = min..max

  // average execution time of 6.94471 milliseconds over 100 iterations
  val result = range.iterator().flatMap { a -> (range.iterator() map { b -> bigInt(a).pow(b) }) }.toSet().size()

  println("there are $result distinct terms in the sequence generated by a^b for both a and b within [$min, $max]")
}
